language: php
dist: trusty

git:
  depth: 2

matrix:
  include:
    - php: 7.1
      env: LINT=true
    - php: nightly
    - php: 7.0
    - php: hhvm-nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
  - phpenv config-rm xdebug.ini || true
#  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - if [ "${LINT}" = "true" ]; then composer lint; fi
  - composer test
